export const data = [
  {
    //EL MISMO PARA TODOS
    PROJECT_NAME: "PROYECTO DE PRUEBA DEFINITIVO",
    //EL MISMO PARA TODOS
    PROJECT_MANAGER: "EDWIN ROMERO",
    //UN DIA DIFERENTE
    DATE: "2021-09-01",
    STATE: "IN PROGRESS",
    SITE_HEALTH: "OK",
  },
  {
    //EL MISMO PARA TODOS
    PROJECT_NAME: "PROYECTO DE PRUEBA DEFINITIVO",
    //EL MISMO PARA TODOS
    PROJECT_MANAGER: "EDWIN ROMERO",
    //UN DIA DIFERENTE
    DATE: "2021-09-02",
    STATE: "IN PROGRESS",
    SITE_HEALTH: "OK",
  },
  {
    //EL MISMO PARA TODOS
    PROJECT_NAME: "PROYECTO DE PRUEBA DEFINITIVO",
    //EL MISMO PARA TODOS
    PROJECT_MANAGER: "EDWIN ROMERO",
    //UN DIA DIFERENTE
    DATE: "2021-09-03",
    STATE: "IN PROGRESS",
    SITE_HEALTH: "OK",
  },
  {
    //EL MISMO PARA TODOS
    PROJECT_NAME: "PROYECTO DE PRUEBA DEFINITIVO",
    //EL MISMO PARA TODOS
    PROJECT_MANAGER: "EDWIN ROMERO",
    //UN DIA DIFERENTE
    DATE: "2021-09-04",
    STATE: "IN PROGRESS",
    SITE_HEALTH: "OK",
  },
  {
    //EL MISMO PARA TODOS
    PROJECT_NAME: "PROYECTO DE PRUEBA DEFINITIVO",
    //EL MISMO PARA TODOS
    PROJECT_MANAGER: "EDWIN ROMERO",
    //UN DIA DIFERENTE
    DATE: "2021-09-05",
    STATE: "IN PROGRESS",
    SITE_HEALTH: "OK",
  },
  {
    //EL MISMO PARA TODOS
    PROJECT_NAME: "PROYECTO DE PRUEBA DEFINITIVO",
    //EL MISMO PARA TODOS
    PROJECT_MANAGER: "EDWIN ROMERO",
    //UN DIA DIFERENTE
    DATE: "2021-09-06",
    STATE: "IN PROGRESS",
    SITE_HEALTH: "OK",
  },
  {
    //EL MISMO PARA TODOS
    PROJECT_NAME: "PROYECTO DE PRUEBA DEFINITIVO",
    //EL MISMO PARA TODOS
    PROJECT_MANAGER: "EDWIN ROMERO",
    //UN DIA DIFERENTE
    DATE: "2021-09-07",
    STATE: "IN PROGRESS",
    SITE_HEALTH: "OK",
  },
];
